### ISSUE TITLE
cannot find module 'crypto'

### ISSUE THREAD

**Issue by ip192** [yunnysunny/node-getui#1]
当我用npm载入个推nodesdk后，会在require('node-getui')时，报找不到'crypto'这个模块的错误，但是在node_module里是有已经添加了的'crypto'的。

**Comment by yunnysunny** [comment]
我刚刚升级了一版，你把之前的getui删除掉，然后重新安装一遍

**Comment by yunnysunny** [comment]
更新了一版，请删除后重新安装一下

**Comment by ip192** [comment]
嗯，好了，一开始的时候没有在package.json里加入个推的依赖，不知道有没有影响。
