### ISSUE TITLE
npm信息修正

### ISSUE THREAD

**Issue by killagu** [yunnysunny/node-getui#3]
刚刚合并 #2 的PR，我把npm信息改成我的了，你这边最好把npm的信息改回来把。
涉及到了package.json中的name,author, repository

**Comment by yunnysunny** [comment]
@killa123 请提供你的邮箱地址，我把你加入contributors中

**Comment by killagu** [comment]
killa123@126.com @yunnysunny

**Comment by yunnysunny** [comment]
已经推送到npm上了
